### ISSUE TITLE
Invite expired

### ISSUE THREAD

**Issue by lunakurame** [Pizzacus/dm-akari.today#1]
Can't join Chiaki Fan Club, because the invite link expired! D: Update pls.

**Comment by Pizzacus** [comment]
yeah they removed all invites for some reason and you can't even make new ones you have to use theirs which is rly stupid lmao

**Comment by Pizzacus** [comment]
Fixed with 49901cda3c481e9974ebbb95baeb683ac9d4537b

**Comment by lunakurame** [comment]
Wow! A fix after exactly 3 years! :D Thank you, Pizza!!!
